name: "Cach builds"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cach:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=./
    - uses: cachix/cachix-action@v8
      with:
        name: bkkp
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Cach builds
      run: nix-build cach.nix
