name: "Update sources"
on: 
  schedule:
    - cron:  '7 * * * *' # UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=./
    - uses: cachix/cachix-action@v8
      with:
        name: bkkp
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Setup git
      run: |
        git config user.name 'GitHub'
        git config user.email 'noreply@github.com'

    - name: Check and update sources.nix
      run: nix-shell --run "niv init"
    - name: Commit changes
      continue-on-error: true
      run: git commit -am "Update sources.nix"

    - name: Update sources
      run: nix-shell --run "niv update"
    - name: Commit changes
      continue-on-error: true
      run: git commit -am "Update nix sources"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "[automation] Update niv sources"
        body: "Daily update of Niv sources."
        branch: "automation/update-niv-sources"
        reviewers: kfollesdal
