name: "Update sources"
on: [push]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=./

    - name: list
      run: ls

    - name: Check and update sources.nix
      run: nix-shell shell.nix --run "niv"

    - name: Update sources
      run: nix-shell --run "niv update"