name: "Update sources"
on: [push]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=./
    - uses: cachix/cachix-action@v8
      with:
        name: bkkp
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Setup git
      run: |
        git config user.name 'GitHub'
        git config user.email 'noreply@github.com'

    - name: Check and update sources.nix
      run: |
        nix-shell --run "niv init"
        git commit -am "Update source.nix"

    - name: Update sources
      run: |
        nix-shell --run "niv update"
        git commit -am "Update niv sources"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "[automation] Update iv dependencies"
        title: "[automation] Update niv sources"
        branch: "automation/update-niv-dependencies"
        reviewers: kfollesdal