name: "Update sources"
on:
  schedule:
    - cron: '0 7 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=./

    - name: Check and update sources.nix
    - run: niv init

    - name: Update sources
    - run: niv update